# Generated by Django 6.0.1 on 2026-01-20 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='recordings/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='stato.match')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerEventInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('shots', 'Shots'), ('passes', 'Passes'), ('touches', 'Touches'), ('duels_won', 'Duels Won'), ('duels_lost', 'Duels Lost'), ('fouls', 'Fouls'), ('interceptions', 'Interceptions'), ('blocks', 'Blocks')], max_length=32)),
                ('second', models.PositiveIntegerField(blank=True, null=True)),
                ('zone', models.CharField(blank=True, max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_instances', to='stato.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_instances', to='stato.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_instances', to='stato.team')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
