# Generated by Django 5.2.7 on 2026-01-20 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stato', '0002_matchrecording_playereventinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='elapsed_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='first_half_duration',
            field=models.PositiveIntegerField(blank=True, default=2700, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='formation',
            field=models.CharField(blank=True, choices=[('4-4-2', '4-4-2'), ('4-3-3', '4-3-3'), ('3-5-2', '3-5-2'), ('4-2-3-1', '4-2-3-1'), ('3-4-3', '3-4-3'), ('5-3-2', '5-3-2'), ('4-1-4-1', '4-1-4-1'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_formation',
            field=models.CharField(blank=True, choices=[('4-4-2', '4-4-2'), ('4-3-3', '4-3-3'), ('3-5-2', '3-5-2'), ('4-2-3-1', '4-2-3-1'), ('3-4-3', '3-4-3'), ('5-3-2', '5-3-2'), ('4-1-4-1', '4-1-4-1'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='state',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('first_half', 'First Half'), ('half_time', 'Half Time'), ('second_half', 'Second Half'), ('finished', 'Finished')], default='not_started', max_length=20),
        ),
        migrations.CreateModel(
            name='OppositionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('shots', 'Shots'), ('passes', 'Passes'), ('touches', 'Touches'), ('duels_won', 'Duels Won'), ('duels_lost', 'Duels Lost'), ('fouls', 'Fouls'), ('interceptions', 'Interceptions'), ('blocks', 'Blocks')], max_length=32)),
                ('count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opposition_stats', to='stato.match')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('match', 'event'), name='uniq_match_opposition_event')],
            },
        ),
    ]
