# Generated by Django 5.2.7 on 2026-01-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stato', '0004_profile_player_alter_profile_role_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
