# Generated by Django 5.2.7 on 2026-01-20 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stato', '0005_team_team_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='goals_conceded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='goals_scored',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.CharField(blank=True, help_text='Format: YYYY/YY (e.g., 2024/25)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='xg',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Expected Goals for', max_digits=5),
        ),
        migrations.AddField(
            model_name='match',
            name='xg_against',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Expected Goals Against', max_digits=5),
        ),
        migrations.AlterField(
            model_name='oppositionstat',
            name='event',
            field=models.CharField(choices=[('shots', 'Shots'), ('shots_on_target', 'Shots on Target'), ('shots_off_target', 'Shots off Target'), ('passes', 'Passes'), ('key_passes', 'Key Passes'), ('duels_won', 'Duels Won'), ('duels_lost', 'Duels Lost'), ('fouls', 'Fouls'), ('interceptions', 'Interceptions'), ('blocks', 'Blocks'), ('tackles', 'Tackles'), ('clearances', 'Clearances')], max_length=32),
        ),
        migrations.AlterField(
            model_name='playereventinstance',
            name='event',
            field=models.CharField(choices=[('shots', 'Shots'), ('shots_on_target', 'Shots on Target'), ('shots_off_target', 'Shots off Target'), ('passes', 'Passes'), ('key_passes', 'Key Passes'), ('duels_won', 'Duels Won'), ('duels_lost', 'Duels Lost'), ('fouls', 'Fouls'), ('interceptions', 'Interceptions'), ('blocks', 'Blocks'), ('tackles', 'Tackles'), ('clearances', 'Clearances')], max_length=32),
        ),
        migrations.AlterField(
            model_name='playereventstat',
            name='event',
            field=models.CharField(choices=[('shots', 'Shots'), ('shots_on_target', 'Shots on Target'), ('shots_off_target', 'Shots off Target'), ('passes', 'Passes'), ('key_passes', 'Key Passes'), ('duels_won', 'Duels Won'), ('duels_lost', 'Duels Lost'), ('fouls', 'Fouls'), ('interceptions', 'Interceptions'), ('blocks', 'Blocks'), ('tackles', 'Tackles'), ('clearances', 'Clearances')], max_length=32),
        ),
        migrations.CreateModel(
            name='ZoneAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(blank=True, help_text='Format: YYYY/YY (e.g., 2024/25)', max_length=10, null=True)),
                ('zone', models.CharField(choices=[('1', 'Zone 1'), ('2', 'Zone 2'), ('3', 'Zone 3'), ('4', 'Zone 4'), ('5', 'Zone 5'), ('6', 'Zone 6')], max_length=8)),
                ('zone_type', models.CharField(choices=[('strength', 'Strength'), ('weakness', 'Weakness')], max_length=10)),
                ('events_in_zone', models.PositiveIntegerField(default=0)),
                ('successful_events', models.PositiveIntegerField(default=0)),
                ('failed_events', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Manual notes about this zone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_analyses', to='stato.team')),
            ],
            options={
                'ordering': ['zone', 'zone_type'],
                'constraints': [models.UniqueConstraint(fields=('team', 'season', 'zone', 'zone_type'), name='uniq_team_season_zone_type')],
            },
        ),
    ]
