# Generated by Django 6.0.1 on 2026-01-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stato', '0006_match_goals_conceded_match_goals_scored_match_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_home',
            field=models.BooleanField(default=True, help_text='True if home match, False if away'),
        ),
        migrations.AlterField(
            model_name='oppositionstat',
            name='event',
            field=models.CharField(choices=[('shots_on_target', 'Shots on Target'), ('shots_off_target', 'Shots off Target'), ('key_passes', 'Key Passes'), ('duels_won', 'Duels Won'), ('duels_lost', 'Duels Lost'), ('fouls', 'Fouls'), ('interceptions', 'Interceptions'), ('blocks', 'Blocks'), ('tackles', 'Tackles'), ('clearances', 'Clearances')], max_length=32),
        ),
        migrations.AlterField(
            model_name='playereventinstance',
            name='event',
            field=models.CharField(choices=[('shots_on_target', 'Shots on Target'), ('shots_off_target', 'Shots off Target'), ('key_passes', 'Key Passes'), ('duels_won', 'Duels Won'), ('duels_lost', 'Duels Lost'), ('fouls', 'Fouls'), ('interceptions', 'Interceptions'), ('blocks', 'Blocks'), ('tackles', 'Tackles'), ('clearances', 'Clearances')], max_length=32),
        ),
        migrations.AlterField(
            model_name='playereventstat',
            name='event',
            field=models.CharField(choices=[('shots_on_target', 'Shots on Target'), ('shots_off_target', 'Shots off Target'), ('key_passes', 'Key Passes'), ('duels_won', 'Duels Won'), ('duels_lost', 'Duels Lost'), ('fouls', 'Fouls'), ('interceptions', 'Interceptions'), ('blocks', 'Blocks'), ('tackles', 'Tackles'), ('clearances', 'Clearances')], max_length=32),
        ),
    ]
