# Generated by Django - remove OppositionStat; opposition comparison is formation-only (Match.opponent_formation)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stato', '0007_match_is_home_alter_oppositionstat_event_and_more'),
    ]

    operations = [
        migrations.DeleteModel(name='OppositionStat'),
    ]
